from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CardStrings:
    top_pill: str
    source_label: str
    chart_label_prefix: str
    cta_question: str
    cta_sub: str
    ai_footer: str


_LOCALIZED_CARDS = {
    "pt": CardStrings(
        top_pill="VÍDEO ORIGINAL ｜ CONTEÚDO REESCRITO",
        source_label="Fonte:",
        chart_label_prefix="Gráfico gerado a partir dos dados: ",
        cta_question="Qual é a sua opinião?",
        cta_sub="Comente o que você pensa abaixo",
        ai_footer="Curta gerado com auxílio de IA",
    ),
    "en": CardStrings(
        top_pill="ORIGINAL SHORT ｜ REWRITTEN CONTENT",
        source_label="Source:",
        chart_label_prefix="Chart regenerated from data: ",
        cta_question="What do you think?",
        cta_sub="Share your thoughts in the comments",
        ai_footer="Short video automatically generated by AI",
    ),
    "zh": CardStrings(
        top_pill="原創短影音 ｜ 內容已重新改寫",
        source_label="資料來源：",
        chart_label_prefix="圖表由資料重新生成：",
        cta_question="你怎麼看？",
        cta_sub="留言分享你的想法",
        ai_footer="短片由 AI 自動生成",
    ),
}


def normalize_lang(language: str | None) -> str:
    """Normalize language code or name to standard short key (pt, en, zh, etc.)."""
    lang = (language or "").strip().lower()
    if any(marker in lang for marker in ("pt", "portug", "português", "portugues")):
        return "pt"
    if any(marker in lang for marker in ("en", "english", "inglês", "ingles", "英语", "英文")):
        return "en"
    if any(marker in lang for marker in ("zh", "chinese", "chinês", "chines", "中文", "繁體", "簡體", "mandarin")):
        return "zh"
    return "en"


def get_card_strings(language: str | None) -> CardStrings:
    key = normalize_lang(language)
    return _LOCALIZED_CARDS.get(key, _LOCALIZED_CARDS["en"])


def citation_text(language: str | None, source_name: str) -> str:
    key = normalize_lang(language)
    clean_source = source_name.strip()
    if key == "pt":
        return f"Segundo apurado por {clean_source}"
    if key == "zh":
        return f"根據 {clean_source} 報導"
    return f"According to {clean_source}'s reporting"


def fallback_source_name(language: str | None) -> str:
    key = normalize_lang(language)
    if key == "pt":
        return "a fonte original"
    if key == "zh":
        return "該影片來源"
    return "the original source"


def script_length_guideline(language: str | None) -> str:
    key = normalize_lang(language)
    if key == "zh":
        return "between 50 and 110 characters (roughly 15–30 seconds of speech)"
    return "between 40 and 75 words (roughly 15–30 seconds of speech)"
